version: "2"
services:
    etcd-s1:
        image: gcr.io/etcd-development/etcd:v3.5.0
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
            - ETCD_NAME=etcd-s1
            - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-s1:2380
            - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
            - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
            - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-s1:2379
            - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
            - ETCD_INITIAL_CLUSTER=etcd-s1=http://etcd-s1:2380,etcd-s2=http://etcd-s2:2380,etcd-s3=http://etcd-s3:2380
            - ETCD_INITIAL_CLUSTER_STATE=new
        container_name: etcd-s1
    etcd-s2:
        image: gcr.io/etcd-development/etcd:v3.5.0
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
            - ETCD_NAME=etcd-s2
            - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-s2:2380
            - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
            - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
            - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-s2:2379
            - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
            - ETCD_INITIAL_CLUSTER=etcd-s1=http://etcd-s1:2380,etcd-s2=http://etcd-s2:2380,etcd-s3=http://etcd-s3:2380
            - ETCD_INITIAL_CLUSTER_STATE=new
        container_name: etcd-s2
    etcd-s3:
        image: gcr.io/etcd-development/etcd:v3.5.0
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
            - ETCD_NAME=etcd-s3
            - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-s3:2380
            - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
            - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
            - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-s3:2379
            - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
            - ETCD_INITIAL_CLUSTER=etcd-s1=http://etcd-s1:2380,etcd-s2=http://etcd-s2:2380,etcd-s3=http://etcd-s3:2380
            - ETCD_INITIAL_CLUSTER_STATE=new
        container_name: etcd-s3
