version: "2.2"
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
        container_name: elasticsearch
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - "ES_JAAV_OPTS=Xms512m -Xms512m"
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - cluster-name=docker-es
        volumes:
            - "../data/es-data:/usr/share/elasticsearch/data"
    kibana:
        image: docker.elastic.co/kibana/kibana:7.13.3
        container_name: kibana
        depends_on:
            - elasticsearch
        ports:
            - 5601:5601
