version: "2"
services:
    influxdb:
        image: influxdb:1.8.6
        container_name: influxdb
        ports:
            - "8086:8086"
        environment:
            - INFLUXDB_DB=test
            - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
            - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
        volumes:
            - influxdb-storage:/var/lib/influxdb
        privileged: true
    grafana:
        image: grafana/grafana:8.0.3
        container_name: grafana
        ports:
            - "3000:3000"
        volumes:
            - grafana-storage:/var/lib/grafana
            - ./grafana_provisioning:/etc/grafana/provisioning
        depends_on:
            - influxdb
        links:
            - influxdb:influxdb
        environment:
            - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
        privileged: true
volumes:
    influxdb-storage:
    grafana-storage:
