global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    honor_labels: false
    honor_timestamps: true
    sample_limit: 0
    static_configs:
      - targets: [192.168.0.106:9090]
        labels:
          instance: prometheus
  - job_name: linux
    static_configs:
      - targets: [192.168.0.106:9100]
