version: "2"
services:
    grafana:
        image: grafana/grafana:8.0.3
        container_name: grafana
        ports:
            - 3000:3000
        volumes:
            - "../data/grafana:/var/lib/grafana"
            - "../data/grafana/provisioning:/etc/grafana/provisioning"
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_USERS_ALLOW_SIGN_UP=false
        restart: unless-stopped
