version: "3"
services:
    gitlab:
        image: gitlab/gitlab-ce
        restart: always
        container_name: gitlab
        hostname: localhost
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://localhost:9525'
                gitlab_rails['time_zone'] = 'Asia/Shanghai'
                gitlab_rails['gitlab_shell_ssh_port'] = 8022
        volumes:
            - ./config:/etc/gitlab
            - ./config:/var/log/gitlab
            - ./data:/var/opt/gitlab
        ports:
            - "9525:9525"
            - "8022:22"

networks:
    default:
        driver: bridge
