version: "2"
services:
    mysql:
        restart: always
        container_name: mysql
        image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: root
            TZ: Asia/Shanghai
        ports:
            - 3306:3306
        volumes:
            - ./mysql/data:/var/lib/mysql # 挂载数据目录
            - ./mysql/my.cnf:/etc/my.cnf # 挂载配置文件
