version: "2"
services:
    influxdb:
        image: influxdb:1.8.6
        ports:
            - "8086:8086"
        container_name: influxdb
        environment:
            - INFLUXDB_ADMIN_ENABLED=true
            - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
            - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
        volumes:
            - "../data/influxdb-storage:/var/lib/influxdb"
